### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by syzer** [stylesuxx/generator-es6-graphql#3]
nvm use 5.5
babel-node --version

```
6.4.0
```

npm start                                                          20 s

```
> login-example@0.0.0 start /Users/lukasgin/liip/js/graphQL/with-login
> babel-node --eval "require('./tools/start').default().catch(err => console.error(err.stack))"

Error: Cannot find module 'lodash/object/merge'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (config.js:3:1)
    at Module._compile (module.js:541:32)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

```

**Comment by stylesuxx** [comment]
Looking into this, can confirm it right now. Will release a new version soon.

**Comment by stylesuxx** [comment]
Fixed in develop branch, will be part of next release. Thanks for your contribution.
